(() => {
'use strict';
// 表示文言の唯一の参照先
let C, db=null, chosen=new Set(), search='', saved=true;
const root=document.getElementById('app');
const key='house-workbook-private-v3:'+location.pathname.replace(/index\.html$/,'');
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n};
const add=(parent,...nodes)=>{parent.append(...nodes);return parent};
const btn=(text,fn,cls='')=>{const n=el('button','btn '+cls,text);n.type='button';n.addEventListener('click',fn);return n};
const find=(id)=>document.getElementById(id);
const label=(id)=>db.labels.find(x=>x.id===id);
const group=(id)=>label(id)?.group;
const labels=(item,g)=>item.labels.map(label).filter(x=>x&&(!g||x.group===g));
const setStatus=(text,isError=false)=>{const bar=find('state');if(bar){bar.firstChild.textContent=text;bar.classList.toggle('error',isError)}};
const verify=(v)=>{
 if(!v||v.version!==2||!Array.isArray(v.items)||!Array.isArray(v.labels)||v.items.length>5000||v.labels.length>500)return false;
 const ids=new Set();
 for(const x of v.labels){if(!x||typeof x.id!=='string'||typeof x.name!=='string'||!C.groups.includes(x.group)||x.id.length>80||x.name.length>100||ids.has(x.id))return false;ids.add(x.id)}
 const itemIds=new Set();
 for(const x of v.items){if(!x||typeof x.id!=='string'||typeof x.title!=='string'||x.id.length>80||x.title.length>400||!Array.isArray(x.labels)||x.labels.some(id=>!ids.has(id))||itemIds.has(x.id))return false;itemIds.add(x.id);for(const k of ['detail','memo'])if(x[k]!=null&&(typeof x[k]!=='string'||x[k].length>20000))return false;if(x.related!=null&&(!Array.isArray(x.related)||x.related.some(t=>typeof t!=='string'||t.length>150)))return false}
 return true;
};
const persist=()=>{try{localStorage.setItem(key,JSON.stringify(db));saved=true;setStatus(C.statusSaved);return true}catch(e){saved=false;setStatus(C.statusError,true);return false}};
const change=(fn)=>{const previous=JSON.stringify(db);fn();if(!persist()){db=JSON.parse(previous);render();alert(C.unsaved);return false}render();return true};
const filePicker=document.createElement('input');filePicker.type='file';filePicker.accept='.json,application/json';filePicker.className='hidden';document.body.append(filePicker);
async function importFile(file){
 if(!file)return;
 if(file.size>2_000_000){alert(C.fileTooLarge);return}
 try{const obj=JSON.parse(await file.text());if(!verify(obj))throw Error(C.fileInvalid);
 if(db&&!confirm(C.confirmReplace))return;
 const previous=db;db=obj;chosen.clear();search='';if(!persist()){db=previous;alert(C.unsaved);return}render();setStatus(C.imported)}catch(e){alert(C.statusImportError+'：'+e.message)}
}
filePicker.addEventListener('change',async()=>{await importFile(filePicker.files?.[0]);filePicker.value=''});
const importAction=()=>filePicker.click();
function exportData(){if(!db)return;const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=el('a');a.href=url;a.download=C.backupName+'_'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
// 現在の全項目を共有用の単一HTMLに複製
function exportHtml(){
 if(!db)return;
 const d=document.implementation.createHTMLDocument(C.appTitle+'（共有用）');d.documentElement.lang='ja';
 const make=(tag,text)=>{const n=d.createElement(tag);if(text!==undefined)n.textContent=String(text);return n};
 const viewport=make('meta');viewport.name='viewport';viewport.content='width=device-width,initial-scale=1';d.head.append(viewport);
 const csp=make('meta');csp.httpEquiv='Content-Security-Policy';csp.content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'none'; connect-src 'none'; font-src 'none'; object-src 'none'; frame-src 'none'; form-action 'none'; base-uri 'none'";d.head.append(csp);
 const css=make('style',`*{box-sizing:border-box}html{font-family:system-ui,"Noto Sans JP",sans-serif;color:#262c2a;background:radial-gradient(ellipse at 85% 5%,#f3f0e7,transparent 42%),radial-gradient(ellipse at 10% 95%,#f0f2ec,transparent 42%),#f8f7f3}body{margin:0;min-height:100vh}header{max-width:1260px;margin:auto;padding:34px 24px 25px;border-bottom:1px solid #cfd4cb}header h1{font-family:Georgia,"Yu Mincho",serif;font-size:clamp(27px,3vw,41px);font-weight:500;letter-spacing:.05em;margin:0}header p{margin:7px 0 0;font-size:11px;color:#68716b;letter-spacing:.1em}main{max-width:1260px;margin:auto;padding:28px 24px 65px}.layout{display:grid;grid-template-columns:215px minmax(0,1fr);gap:35px}.filters{align-self:start;position:sticky;top:14px;border-top:1px solid #aebbb0;padding:19px 0}.filters h2{font-family:Georgia,"Yu Mincho",serif;font-size:18px;font-weight:500;margin:0 0 9px}.hint,.count{font-size:11px;color:#68716b;line-height:1.7}.row{padding:13px 0;border-top:1px solid #e0e3db}.row strong{display:block;font-size:11px;color:#59665b;margin-bottom:9px}.chips,.tags{display:flex;flex-wrap:wrap;gap:6px}.chip{display:inline-flex;align-items:center;gap:5px;border:1px solid #d7dcd3;border-radius:3px;background:#ffffffa6;padding:6px 9px;font-size:11px;cursor:pointer}.chip:has(input:checked){background:#e5ece6;color:#264639;border-color:#8ca497}.chip input{margin:0;accent-color:#36594d}input[type=search]{width:100%;min-height:45px;border:0;border-bottom:1px solid #aeb8ad;border-radius:0;padding:10px 2px;background:transparent;font:inherit;font-size:13px}input[type=search]:focus{outline:none;border-bottom:2px solid #36594d}.count{margin:14px 0}.cards{counter-reset:entry;display:grid;gap:9px}.card{counter-increment:entry;position:relative;background:#ffffffd9;border:1px solid #e1e2dc;border-radius:5px;padding:18px 20px 18px 66px;box-shadow:0 5px 19px #3c48380a}.card:before{content:counter(entry,decimal-leading-zero);position:absolute;left:20px;top:20px;font:15px Georgia,serif;color:#88978b}.card h3{font-family:Georgia,"Yu Mincho",serif;font-weight:500;font-size:17px;line-height:1.55;margin:0 0 8px;overflow-wrap:anywhere;color:#293c32}.card p{font-size:12px;line-height:1.85;color:#59645b;margin:7px 0;white-space:pre-wrap;overflow-wrap:anywhere}.tags{margin-top:12px}.tag{font-size:10px;background:#f3f5ef;border:1px solid #e5e9df;border-radius:2px;padding:4px 8px;color:#53665a}.empty{border:1px solid #e1e2dc;background:#ffffffd9;border-radius:5px;padding:24px;text-align:center;font-size:12px}[hidden]{display:none!important}@media(max-width:740px){header{padding:25px 16px 20px}main{padding:17px 14px 40px}.layout{display:block}.filters{position:static;margin-bottom:22px;padding:13px 0}.chips{flex-wrap:nowrap;overflow-x:auto}.chip{flex:none}.card{padding:15px 12px 15px 43px}.card:before{left:12px;top:17px;font-size:12px}.card h3{font-size:16px}}`);d.head.append(css);
 const header=make('header');header.append(make('h1',C.appTitle),make('p','共有用・閲覧専用'));d.body.append(header);
 const main=make('main'),layout=make('div'),filters=make('aside'),content=make('section');layout.className='layout';filters.className='filters';filters.append(make('h2',C.filtersTitle),make('p',C.filterHint));
 for(const g of C.groups){const ls=db.labels.filter(x=>x.group===g);if(!ls.length)continue;const row=make('div'),chips=make('div');row.className='row';chips.className='chips';row.append(make('strong',g));for(const l of ls){const chip=make('label'),check=make('input');chip.className='chip';check.type='checkbox';check.value=l.id;check.setAttribute('aria-label',g+'：'+l.name);chip.append(check,make('span',l.name));chips.append(chip)}row.append(chips);filters.append(row)}
 const searchBox=make('input'),count=make('p'),cards=make('div'),empty=make('div',db.items.length?C.empty:C.noItems);searchBox.type='search';searchBox.placeholder=C.searchPlaceholder;searchBox.setAttribute('aria-label',C.searchPlaceholder);count.className='count';cards.className='cards';empty.className='empty';empty.hidden=true;
 const names=new Map(db.labels.map(l=>[l.id,l.name]));for(const item of db.items){const card=make('article');card.className='card';card.dataset.labels=JSON.stringify(item.labels);card.dataset.search=[item.title,item.detail,item.memo,...(item.related||[]),...item.labels.map(id=>names.get(id)||'')].join(' ').toLocaleLowerCase();card.append(make('h3',item.title));if(item.detail)card.append(make('p',item.detail));if(item.memo)card.append(make('p',C.memo+'：'+item.memo));if(item.related?.length)card.append(make('p',C.related+'：'+item.related.join(' / ')));const tags=make('div');tags.className='tags';for(const id of item.labels)if(names.has(id)){const tag=make('span',names.get(id));tag.className='tag';tags.append(tag)}card.append(tags);cards.append(card)}
 content.append(searchBox,count,cards,empty);layout.append(filters,content);main.append(layout);d.body.append(main);
 const script=make('script',`(()=>{'use strict';const search=document.querySelector('input[type="search"]'),checks=[...document.querySelectorAll('input[type="checkbox"]')],cards=[...document.querySelectorAll('article.card')],count=document.querySelector('.count'),empty=document.querySelector('.empty');function update(){const selected=checks.filter(x=>x.checked).map(x=>x.value),q=search.value.trim().toLocaleLowerCase();let n=0;for(const card of cards){const show=selected.every(id=>JSON.parse(card.dataset.labels).includes(id))&&(!q||card.dataset.search.includes(q));card.hidden=!show;if(show)n++}count.textContent=n+' 件を表示';empty.hidden=n!==0}search.addEventListener('input',update);for(const check of checks)check.addEventListener('change',update);update()})();`);d.body.append(script);
 const blob=new Blob(['<!doctype html>\n'+d.documentElement.outerHTML],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=C.appTitle+'_共有用_'+new Date().toISOString().slice(0,10)+'.html';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)
}
function render(){
 document.title=C.appTitle;
 root.replaceChildren();
 const mast=el('header','mast'),mi=el('div','mastInner');add(mi,el('div','eyebrow',C.eyebrow),el('h1','',C.appTitle),el('p','',C.subtitle));
 const actions=el('div','actions');
 add(actions,btn(C.importAgain,importAction),btn(C.export,exportData),btn(C.exportHtml,exportHtml),btn(C.add,()=>edit(null),'primary'),btn(C.labelsManage,manageLabels));
 if(!db)actions.classList.add('hidden');add(mi,actions);add(mast,mi);root.append(mast);
 const shell=el('main','shell');root.append(shell);
 if(!db){const onboard=el('section','onboard');add(onboard,el('h2','',C.firstTitle),el('p','',C.firstDescription),btn(C.importFirst,importAction,'primary'),el('p','muted',C.privacy));shell.append(onboard);return}
 const intro=el('section','topCard');add(intro,el('h2','',C.description),el('p','',C.intro));shell.append(intro);
 const layout=el('div','layout'),side=el('aside','side');add(side,el('h3','',C.filtersTitle),el('p','',C.filterHint),el('p','',C.privacy),btn(C.export,exportData));
 const content=el('section','content');const state=el('div','statebar');state.id='state';add(state,el('span','',saved?C.statusReady:C.statusError),el('span','',C.statusLocal));if(!saved)state.classList.add('error');content.append(state);
 const quick=el('div','quick');for(const [name,arr] of [[C.presetContract,C.presetContractLabels],[C.presetTodo,C.presetTodoLabels],[C.presetAll,[]]])add(quick,btn(name,()=>{chosen=new Set(arr.map(t=>db.labels.find(x=>x.name===t)?.id).filter(Boolean));search='';render()}));content.append(quick);
 const panel=el('section','panel'),head=el('div','panelHead');add(head,el('h3','',C.filtersTitle),btn(C.clear,()=>{chosen.clear();search='';render()}));add(panel,head,el('p','hint',C.filterHint));
 for(const g of C.groups){const arr=db.labels.filter(x=>x.group===g);if(!arr.length)continue;const row=el('div','filterRow'),chips=el('div','chips');row.append(el('strong','',g));for(const x of arr){const b=btn(x.name,()=>{chosen.has(x.id)?chosen.delete(x.id):chosen.add(x.id);render()});b.className='chip '+(C.groupColor[g]||'')+(chosen.has(x.id)?' active':'');b.setAttribute('aria-pressed',String(chosen.has(x.id)));chips.append(b)}add(row,chips);panel.append(row)}content.append(panel);
 const input=el('input','search');input.type='search';input.placeholder=C.searchPlaceholder;input.value=search;input.setAttribute('aria-label',C.searchPlaceholder);content.append(input);
 const count=el('p','count'),cards=el('div','cards');content.append(count,cards);
 const paint=()=>{search=input.value.trim().toLocaleLowerCase();cards.replaceChildren();const items=db.items.filter(x=>[...chosen].every(id=>x.labels.includes(id))&&(!search||[x.title,x.detail,x.memo,...(x.related||[]),...x.labels.map(id=>label(id)?.name||'')].join(' ').toLocaleLowerCase().includes(search)));count.textContent=items.length+' '+C.results;
 for(const item of items){const card=el('article','card'),top=el('div','cardTop'),body=el('div'),buttons=el('div','cardButtons');body.append(el('h3','',item.title));if(item.detail)body.append(el('p','',item.detail));
 add(buttons,btn(C.status,()=>cycleStatus(item.id)),btn(C.edit,()=>edit(item.id)));add(top,body,buttons);card.append(top);
 if(item.memo)card.append(el('p','',C.memo+'：'+item.memo));if(item.related?.length)card.append(el('p','muted',C.related+'：'+item.related.join(' / ')));
 const tags=el('div','tags');for(const l of item.labels.map(label).filter(Boolean))tags.append(el('span','tag',l.name));card.append(tags);cards.append(card)}
 if(!items.length)cards.append(el('div','empty',db.items.length?C.empty:C.noItems))};
 input.addEventListener('input',paint);paint();add(layout,side,content);shell.append(layout)
}
function cycleStatus(id){const item=db.items.find(x=>x.id===id);if(!item)return;const all=db.labels.filter(x=>x.group===C.groupStatus);if(!all.length)return;const current=labels(item,C.groupStatus)[0];const next=all[(all.findIndex(x=>x.id===current?.id)+1)%all.length];change(()=>{item.labels=item.labels.filter(x=>group(x)!==C.groupStatus);item.labels.push(next.id)})}
function modal(title){const d=el('dialog','dialog'),head=el('div','dialogHead'),body=el('div','dialogBody'),foot=el('div','dialogFoot');add(head,el('h2','',title),btn(C.close,()=>d.close()));add(d,head,body,foot);document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();return{d,body,foot}}
function inputField(parent,name,value,multi=false){parent.append(el('label','fieldLabel',name));const n=el(multi?'textarea':'input','fieldInput'+(multi?' area':''));n.value=value||'';n.setAttribute('aria-label',name);if(!multi)n.type='text';parent.append(n);return n}
function edit(id){if(!db)return;const item=db.items.find(x=>x.id===id),m=modal(item?C.editItem:C.newItem);const title=inputField(m.body,C.title,item?.title),detail=inputField(m.body,C.detail,item?.detail,true),memo=inputField(m.body,C.memo,item?.memo,true),related=inputField(m.body,C.related,item?.related?.join(' / '));const checked=new Set(item?.labels||[]);
 for(const g of C.groups){const options=db.labels.filter(x=>x.group===g);if(!options.length)continue;const section=el('div','editGroup'),chips=el('div','chips');section.append(el('strong','',g));for(const l of options){const b=btn(l.name,()=>{if(checked.has(l.id))checked.delete(l.id);else{if(C.singleGroups.includes(g))for(const x of options)checked.delete(x.id);checked.add(l.id)}for(const x of chips.children)x.classList.toggle('active',checked.has(x.dataset.id))});b.dataset.id=l.id;b.className='chip'+(checked.has(l.id)?' active':'');chips.append(b)}section.append(chips);m.body.append(section)}
 if(item)m.foot.append(btn(C.delete,()=>{if(confirm(C.confirmDelete))change(()=>db.items=db.items.filter(x=>x.id!==id))&&m.d.close()},'danger'));
 add(m.foot,btn(C.cancel,()=>m.d.close()),btn(C.save,()=>{const t=title.value.trim();if(!t){alert(C.required);title.focus();return}if(change(()=>{const data={title:t,detail:detail.value.trim(),memo:memo.value.trim(),related:related.value.split(/[、,，/\n]/).map(x=>x.trim()).filter(Boolean),labels:[...checked]};if(item)Object.assign(item,data);else db.items.push({id:crypto.randomUUID(),order:db.items.length,...data})}))m.d.close()},'primary'));title.focus()}
function manageLabels(){if(!db)return;const m=modal(C.labelsManage),list=el('div');m.body.append(list);
 const redraw=()=>{list.replaceChildren();for(const l of db.labels){const row=el('div','labelRow'),name=el('input','fieldInput');name.value=l.name;name.setAttribute('aria-label',C.labelName+' '+l.name);name.addEventListener('change',()=>{const val=name.value.trim();if(!val||db.labels.some(x=>x!==l&&x.group===l.group&&x.name===val)){alert(C.duplicateLabel);name.value=l.name;return}change(()=>{const old=l.name;l.name=val;if(l.group===C.groupField)for(const i of db.items)i.related=(i.related||[]).map(x=>x===old?val:x)});redraw()});add(row,el('small','',l.group),name,el('small','',db.items.filter(i=>i.labels.includes(l.id)).length+' '+C.labelCount),btn(C.delete,()=>{if(C.singleGroups.includes(l.group)&&db.labels.filter(x=>x.group===l.group).length<2){alert(C.confirmLastLabel);return}if(confirm(C.confirmDeleteLabel)){change(()=>{db.labels=db.labels.filter(x=>x!==l);for(const i of db.items)i.labels=i.labels.filter(x=>x!==l.id);chosen.delete(l.id)});redraw()}},'danger'));list.append(row)}};
 redraw();const row=el('div','addLabelRow'),sel=el('select','fieldInput');sel.setAttribute('aria-label',C.labelGroup);for(const g of C.groups){const o=el('option','',g);o.value=g;sel.append(o)}const name=el('input','fieldInput');name.placeholder=C.labelName;name.setAttribute('aria-label',C.labelName);add(row,sel,name,btn(C.addLabel,()=>{const v=name.value.trim();if(!v)return;if(db.labels.some(x=>x.group===sel.value&&x.name===v)){alert(C.duplicateLabel);return}if(change(()=>db.labels.push({id:crypto.randomUUID(),group:sel.value,name:v}))){name.value='';redraw()}}));m.body.append(row);m.foot.append(btn(C.close,()=>m.d.close()))}
async function start(){try{const res=await fetch('./config.json',{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});if(!res.ok)throw Error();C=await res.json();if(!C||!Array.isArray(C.groups)||!C.appTitle)throw Error();try{const savedData=localStorage.getItem(key);if(savedData){const parsed=JSON.parse(savedData);if(!verify(parsed))throw Error();db=parsed}}catch(e){saved=false;db=null}render()}catch(e){root.replaceChildren()}}
start();
})();